# Numpy and pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Creating Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
# Basic Operations
print(arr + 10)
print(arr * 2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [4]:
# Shape and Reshape
matrix = np.arange(1, 13).reshape(4, 3)
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
data = {'Name': ['Ali', 'Sara', 'John','Ali'],
 'Age': [25, 30, 28,25],
 'City': ['Karachi', 'Lahore', 'Islamabad','Karachi']}
df = pd.DataFrame(data)
print(df)

   Name  Age       City
0   Ali   25    Karachi
1  Sara   30     Lahore
2  John   28  Islamabad
3   Ali   25    Karachi


In [6]:
# Accessing Columns
print(df['Name'])

0     Ali
1    Sara
2    John
3     Ali
Name: Name, dtype: object


In [7]:
# Accessing Columns
print(df['City'])

0      Karachi
1       Lahore
2    Islamabad
3      Karachi
Name: City, dtype: object


In [8]:
# Accessing Columns
print(df['Age'])

0    25
1    30
2    28
3    25
Name: Age, dtype: int64


In [9]:
df.to_excel("UzairSales.xlsx",index_label="Names")

In [10]:
# Adding New Column
df['Salary'] = [50000, 60000, 70000,50000]

In [11]:
df

Name  Age       City  Salary
0   Ali   25    Karachi   50000
1  Sara   30     Lahore   60000
2  John   28  Islamabad   70000
3   Ali   25    Karachi   50000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
 3   Salary  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes


In [13]:
df.describe()

Age        Salary
count   4.00000      4.000000
mean   27.00000  57500.000000
std     2.44949   9574.271078
min    25.00000  50000.000000
25%    25.00000  50000.000000
50%    26.50000  55000.000000
75%    28.50000  62500.000000
max    30.00000  70000.000000

In [14]:
df.Age

0    25
1    30
2    28
3    25
Name: Age, dtype: int64

In [15]:
df.value_counts()

Name  Age  City       Salary
Ali   25   Karachi    50000     2
John  28   Islamabad  70000     1
Sara  30   Lahore     60000     1
dtype: int64

In [16]:
df

Name  Age       City  Salary
0   Ali   25    Karachi   50000
1  Sara   30     Lahore   60000
2  John   28  Islamabad   70000
3   Ali   25    Karachi   50000

# Massive Bank Data

In [17]:
data=pd.read_excel('bankdataset.xlsx')

In [18]:
data

Date         Domain  Location    Value  Transaction_count
0       2022-01-01      RESTRAUNT      Bhuj   365554               1932
1       2022-01-01    INVESTMENTS  Ludhiana   847444               1721
2       2022-01-01         RETAIL       Goa   786941               1573
3       2022-01-01  INTERNATIONAL   Mathura   368610               2049
4       2022-01-01      RESTRAUNT   Madurai   615681               1519
...            ...            ...       ...      ...                ...
1004475 2022-12-31  INTERNATIONAL    Konark   738557                754
1004476 2022-12-31    INVESTMENTS      Pune   668180               1572
1004477 2022-12-31         RETAIL      Durg  1000349               2155
1004478 2022-12-31  INTERNATIONAL   Mathura  1026547               2458
1004479 2022-12-31         RETAIL   Patiala   763159                992

[1004480 rows x 5 columns]

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004480 entries, 0 to 1004479
Data columns (total 5 columns):
 #   Column             Non-Null Count    Dtype         
---  ------             --------------    -----         
 0   Date               1004480 non-null  datetime64[ns]
 1   Domain             1004480 non-null  object        
 2   Location           1004480 non-null  object        
 3   Value              1004480 non-null  int64         
 4   Transaction_count  1004480 non-null  int64         
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 38.3+ MB


In [20]:
data_domain=data['Domain'].unique()

In [21]:
data_domain

array(['RESTRAUNT', 'INVESTMENTS', 'RETAIL', 'INTERNATIONAL', 'PUBLIC',
       'MEDICAL', 'EDUCATION'], dtype=object)

In [22]:
data_domain = pd.DataFrame(data_domain)


In [23]:
data_domain.to_excel("data_domain.xlsx",index_label="Names")

In [38]:
data_date=data['Date'].unique()

In [39]:
data_date

array(['2022-01-01T00:00:00.000000000', '2022-01-02T00:00:00.000000000',
       '2022-01-03T00:00:00.000000000', '2022-01-04T00:00:00.000000000',
       '2022-01-05T00:00:00.000000000', '2022-01-06T00:00:00.000000000',
       '2022-01-07T00:00:00.000000000', '2022-01-08T00:00:00.000000000',
       '2022-01-09T00:00:00.000000000', '2022-01-10T00:00:00.000000000',
       '2022-01-11T00:00:00.000000000', '2022-01-12T00:00:00.000000000',
       '2022-01-13T00:00:00.000000000', '2022-01-14T00:00:00.000000000',
       '2022-01-15T00:00:00.000000000', '2022-01-16T00:00:00.000000000',
       '2022-01-17T00:00:00.000000000', '2022-01-18T00:00:00.000000000',
       '2022-01-19T00:00:00.000000000', '2022-01-20T00:00:00.000000000',
       '2022-01-21T00:00:00.000000000', '2022-01-22T00:00:00.000000000',
       '2022-01-23T00:00:00.000000000', '2022-01-24T00:00:00.000000000',
       '2022-01-25T00:00:00.000000000', '2022-01-26T00:00:00.000000000',
       '2022-01-27T00:00:00.000000000', '2022-01-28

In [82]:
filtered_date=data[(data["Date"] >= "2022-01-01") & (data["Date"] <= "2022-01-31")]

In [83]:
filtered_date

Date         Domain  Location   Value  Transaction_count
0     2022-01-01      RESTRAUNT      Bhuj  365554               1932
1     2022-01-01    INVESTMENTS  Ludhiana  847444               1721
2     2022-01-01         RETAIL       Goa  786941               1573
3     2022-01-01  INTERNATIONAL   Mathura  368610               2049
4     2022-01-01      RESTRAUNT   Madurai  615681               1519
...          ...            ...       ...     ...                ...
85307 2022-01-31      EDUCATION    Ranchi  771286                864
85308 2022-01-31      EDUCATION     Bidar  677155               2002
85309 2022-01-31    INVESTMENTS      Durg  353702                753
85310 2022-01-31        MEDICAL    Kanpur  954733               1813
85311 2022-01-31         PUBLIC     Surat  862859                951

[85312 rows x 5 columns]

In [84]:
filtered_date = pd.DataFrame(filtered_date)
filtered_date.to_excel("filtered_date.xlsx",index_label="Names")

In [85]:
filtered_dates=filtered_date.groupby(['Domain','Location'])['Transaction_count'].sum()

In [87]:
filtered_dates

Domain     Location 
EDUCATION  Ahmedabad    377774
           Ajmer        429500
           Akola        400548
           Ambala       448005
           Amritsar     372851
                         ...  
RETAIL     Surat        398448
           Tirumala     368406
           Trichy       378418
           Varanasi     341004
           Vellore      345939
Name: Transaction_count, Length: 322, dtype: int64

In [88]:
filtered_dates= pd.DataFrame(filtered_dates)

In [89]:
filtered_dates.to_excel("data_domainss.xlsx",index_label="Names")